version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie
    steps:
      - checkout
      - run: sudo npm i -g firebase-tools
      - run: sudo npm i -g ionic
      - run: npm i
      - run: ionic build --prod
      - run: firebase use psicoguia
      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_test:
    jobs:
      - build