# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import medic.models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/static/images/no_user.png', upload_to=medic.models.profileFilePath),
        ),
    ]
