# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 01:28
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('medic', '0002_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addres',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
